# Generated by Django 5.0.4 on 2024-05-02 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalClient',
            fields=[
                ('personal_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('personal_client_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('sector_code', models.CharField(max_length=20)),
                ('sector_label', models.CharField(max_length=150)),
                ('activity_code', models.CharField(max_length=20)),
                ('activity_label', models.CharField(max_length=150)),
                ('product_code', models.CharField(max_length=20)),
                ('product_label', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('producer_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('addresse', models.CharField(max_length=255)),
                ('tax_code', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=100)),
                ('nat_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_producer', to='economic_exchanges.product')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyClient',
            fields=[
                ('company_client_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tax_code', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=100)),
                ('nat_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_company_client', to='economic_exchanges.product')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date', models.DateField()),
                ('company_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_sale', to='economic_exchanges.companyclient')),
                ('personal_client_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_client_sale', to='economic_exchanges.personalclient')),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_sale', to='economic_exchanges.producer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secteur_activite', to='economic_exchanges.product')),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('supplier_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=100)),
                ('manager_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('tax_code', models.CharField(max_length=100)),
                ('nrc', models.CharField(max_length=100)),
                ('nat_id', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_supplier', to='economic_exchanges.product')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('purchase_id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('tva', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('date', models.DateField()),
                ('producer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producer_purchase', to='economic_exchanges.producer')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_purchase', to='economic_exchanges.product')),
                ('supplier_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_purchase', to='economic_exchanges.supplier')),
            ],
        ),
    ]
