# Generated by Django 5.0.4 on 2024-05-03 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='nat_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='nrc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_company_client', to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='companyclient',
            name='tax_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalclient',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personalclient',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='nat_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='nrc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producer',
            name='tax_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nat_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='nrc',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_supplier', to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='tax_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
