# Generated by Django 4.2.11 on 2024-05-07 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='product_id',
            new_name='product',
        ),
    ]
