# Generated by Django 4.2.11 on 2024-05-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0002_alter_companyclient_email_alter_companyclient_nat_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='profile_photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo de profil entreprise'),
        ),
    ]
