# Generated by Django 4.2.11 on 2024-05-07 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0004_alter_producer_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_company_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='personalclient',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_personal_client', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='producer',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_province', to='economic_exchanges.province'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_purchase', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_purchase', to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_purchase', to='economic_exchanges.supplier'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='company_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_sale', to='economic_exchanges.companyclient'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='personal_client_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_client_sale', to='economic_exchanges.personalclient'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_sale', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secteur_activite', to='economic_exchanges.product'),
        ),
    ]
