# Generated by Django 4.2.11 on 2024-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0005_alter_companyclient_producer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='chef_lieu',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
