# Generated by Django 4.2.11 on 2024-05-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0006_province_chef_lieu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo de profil entreprise'),
        ),
    ]
