# Generated by Django 4.2.11 on 2024-05-09 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0007_alter_producer_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='sector_label',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
