# Generated by Django 4.2.11 on 2024-05-09 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0008_producer_sector_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producer',
            name='sector_label',
        ),
    ]
