# Generated by Django 4.2.11 on 2024-05-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0009_remove_producer_sector_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyclient',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='product',
        ),
        migrations.AddField(
            model_name='companyclient',
            name='products',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='products',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='products',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
        migrations.RemoveField(
            model_name='producer',
            name='product',
        ),
        migrations.AddField(
            model_name='producer',
            name='product',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
    ]
