# Generated by Django 4.2.11 on 2024-05-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0010_remove_companyclient_product_remove_purchase_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyclient',
            name='products',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='products',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='products',
        ),
        migrations.AddField(
            model_name='companyclient',
            name='product',
            field=models.ManyToManyField(null=True, to='economic_exchanges.product'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(null=True, to='economic_exchanges.product'),
        ),
        migrations.AddField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(null=True, to='economic_exchanges.product'),
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='product',
        ),
        migrations.AddField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(null=True, to='economic_exchanges.product'),
        ),
    ]
