# Generated by Django 4.2.11 on 2024-05-10 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0011_remove_companyclient_products_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producer_supplier', to=settings.AUTH_USER_MODEL),
        ),
    ]
