# Generated by Django 4.2.11 on 2024-05-10 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0012_supplier_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='product',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='product',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(to='economic_exchanges.product'),
        ),
    ]
