# Generated by Django 4.2.11 on 2024-05-10 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0013_alter_companyclient_product_alter_purchase_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='supplier_id',
            new_name='id',
        ),
    ]
