# Generated by Django 4.2.11 on 2024-05-10 11:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0014_rename_supplier_id_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyclient',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_client_province', to='economic_exchanges.province'),
        ),
    ]
