# Generated by Django 4.2.11 on 2024-05-13 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0015_alter_companyclient_province'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='sector_label',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
