# Generated by Django 4.2.11 on 2024-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0016_producer_sector_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producer',
            name='product',
            field=models.ManyToManyField(blank=True, to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='sector_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
