# Generated by Django 4.2.11 on 2024-05-14 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0017_alter_producer_product_alter_producer_sector_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='producer',
            name='about',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
