# Generated by Django 4.2.11 on 2024-06-08 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('economic_exchanges', '0019_supplier_sector_label_alter_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='product',
            field=models.ManyToManyField(blank=True, to='economic_exchanges.product'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='province',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supplier_province', to='economic_exchanges.province'),
        ),
    ]
